### ISSUE TITLE
Error execute: component not found

### ISSUE THREAD

**Issue by MinionAttack** [emorynlp/nlp4j-old#12]
I'm trying to train with ClearParser and I get this error. Before execute the command I put `export CLASSPATH=nlp4j-1.1.0.jar:.` and doing `java edu.emory.mathcs.nlp.bin.Version` I get the version info, so it's installed correctly.

Command line: `java -Xmx5g -XX:+UseConcMarkSweepGC edu.emory.mathcs.nlp.bin.NLPTrain -mode dep -c config-train-dep.xml -t /home/iago/Escritorio/idiomasClearParser/UD_English/en-ud-train.conllu -d /home/iago/Escritorio/idiomasClearParser/UD_English/en-ud-dev.conllu -m bestModel-dep.xz`

I'm using this config file: [https://github.com/emorynlp/nlp4j/blob/master/src/main/resources/edu/emory/mathcs/nlp/configuration/config-train-dep.xml](url) 

Error: `log4j:WARN No appenders could be found for logger (edu.emory.mathcs.nlp.common.util.BinUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.io.FileNotFoundException: edu/emory/mathcs/nlp/lexica/en-brown-clusters-simplified-lowercase.xz (No existe el archivo o el directorio)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at edu.emory.mathcs.nlp.common.util.IOUtils.createFileInputStream(IOUtils.java:147)
    at edu.emory.mathcs.nlp.common.util.IOUtils.getInputStream(IOUtils.java:316)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.getLexiconFieldPair(GlobalLexica.java:82)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.getLexiconFieldPair(GlobalLexica.java:72)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:64)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:55)
    at edu.emory.mathcs.nlp.bin.NLPTrain$1.createGlobalLexica(NLPTrain.java:108)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:193)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:187)
    at edu.emory.mathcs.nlp.bin.NLPTrain.train(NLPTrain.java:76)
    at edu.emory.mathcs.nlp.bin.NLPTrain.main(NLPTrain.java:115)
java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at java.io.DataInputStream.readFully(DataInputStream.java:195)
    at java.io.DataInputStream.readFully(DataInputStream.java:169)
    at org.tukaani.xz.SingleXZInputStream.initialize(Unknown Source)
    at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source)
    at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
    at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
    at edu.emory.mathcs.nlp.common.util.IOUtils.createXZBufferedInputStream(IOUtils.java:220)
    at edu.emory.mathcs.nlp.common.util.IOUtils.createObjectXZBufferedInputStream(IOUtils.java:259)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.getLexiconFieldPair(GlobalLexica.java:82)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.getLexiconFieldPair(GlobalLexica.java:72)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:64)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:55)
    at edu.emory.mathcs.nlp.bin.NLPTrain$1.createGlobalLexica(NLPTrain.java:108)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:193)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:187)
    at edu.emory.mathcs.nlp.bin.NLPTrain.train(NLPTrain.java:76)
    at edu.emory.mathcs.nlp.bin.NLPTrain.main(NLPTrain.java:115)
Exception in thread "main" java.lang.NullPointerException
    at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2338)
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2351)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
    at edu.emory.mathcs.nlp.common.util.IOUtils.createObjectXZBufferedInputStream(IOUtils.java:259)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.getLexiconFieldPair(GlobalLexica.java:82)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.getLexiconFieldPair(GlobalLexica.java:72)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:64)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:55)
    at edu.emory.mathcs.nlp.bin.NLPTrain$1.createGlobalLexica(NLPTrain.java:108)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:193)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:187)
    at edu.emory.mathcs.nlp.bin.NLPTrain.train(NLPTrain.java:76)
    at edu.emory.mathcs.nlp.bin.NLPTrain.main(NLPTrain.java:115)
`

Why I'm getting this error? I unpacked the .jar and there is no "lexica" folder neither "en-brown-clusters-simplified-lowercase.xz". Where I can found it?

Regards

**Comment by jdchoi77** [comment]
It seems like the lexica file are not added to your classpath.  How are you adding the lexica files (through maven or jar)?  All individual files are available in the following repository:

https://bitbucket.org/emorynlp/nlp4j-english

**Comment by MinionAttack** [comment]
Oh, thanks. I have solved it creating the log4j properties and now adding the lexica files. Thanks!
