### ISSUE TITLE
Exception reading dependency model

### ISSUE THREAD

**Issue by benson-basis** [emorynlp/nlp4j-old#34]
Have you ever seen this?

```
java.lang.IllegalStateException: unread block data
    at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2431)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1383)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at edu.emory.mathcs.nlp.decode.NLPUtils.getComponent(NLPUtils.java:60)
    at edu.emory.mathcs.nlp.decode.AbstractNLPDecoder.init(AbstractNLPDecoder.java:102)
    at edu.emory.mathcs.nlp.decode.AbstractNLPDecoder.<init>(AbstractNLPDecoder.java:65)
    at edu.emory.mathcs.nlp.decode.NLPDecoder.<init>(NLPDecoder.java:36)
```

**Comment by benson-basis** [comment]
This was a jetty classpath issue.
