### ISSUE TITLE
IllegalStateException: unread block data 

### ISSUE THREAD

**Issue by omondigeno** [emorynlp/nlp4j-old#5]
On running the NLPDemo I get the following exception

java.lang.IllegalStateException: unread block data
    at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2431)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1383)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at edu.emory.mathcs.nlp.decode.NLPDecoder.getComponent(NLPDecoder.java:271)
    at edu.emory.mathcs.nlp.decode.NLPDecoder.init(NLPDecoder.java:87)
    at edu.emory.mathcs.nlp.decode.NLPDecoder.<init>(NLPDecoder.java:72)

**Comment by jdchoi77** [comment]
Please make sure you give at least 8gb of RAM to run the entire pipeline.  Please let me know if that doesn't resolve this issue.  Thanks.

best,

Jinho

**Comment by omondigeno** [comment]
Thanks for the quick response. Increasing RAM to at least 8gb resolves the issue. Thanks a lot.
