### ISSUE TITLE
[Fatal Error] :52:71:org.xml.sax.SAXParseException

### ISSUE THREAD

**Issue by MinionAttack** [emorynlp/nlp4j-old#9]
Hi, I'm trying to train a model with a train and dev from Universal Dependencies-1.2 and after adapt it to ClearNLP format I'm getting this error in command line:

`[Fatal Error]: 52: 71: The attribute name "data-pjax-transient" associated with a type of "meta" element must be followed by the character '='.
org.xml.sax.SAXParseException; lineNumber: 52; columnNumber: 71; The name attribute "data-pjax-transient" associated with a type of "meta" element must be followed by the character '='.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at edu.emory.mathcs.nlp.common.util.XMLUtils.getDocumentElement(XMLUtils.java:107)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:55)
    at edu.emory.mathcs.nlp.bin.NLPTrain$1.createGlobalLexica(NLPTrain.java:108)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:193)
    at edu.emory.mathcs.nlp.component.template.train.OnlineTrainer.train(OnlineTrainer.java:187)
    at edu.emory.mathcs.nlp.bin.NLPTrain.train(NLPTrain.java:76)
    at edu.emory.mathcs.nlp.bin.NLPTrain.main(NLPTrain.java:115)
Exception in thread "main" java.lang.NullPointerException
    at edu.emory.mathcs.nlp.common.util.XMLUtils.getFirstElementByTagName(XMLUtils.java:74)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:60)
    at edu.emory.mathcs.nlp.component.template.util.GlobalLexica.<init>(GlobalLexica.java:55)
    at edu.emory.mathcs.nlp.bin.NLPTrain$1.createGlobalLexica(NLPTrain.java:108)`

My train and dev files looks (separator it's '\t'):

1   [   [   PUNCT   _   10  punct   _   _
2   This    this    DET Number=Sing|PronType=Dem    3   det _   _
3   killing killing NOUN    Number=Sing 10  nsubj   _   _
4   of  of  ADP _   7   case    _   _
5   a   a   DET Definite=Ind|PronType=Art   7   det _   _
6   respected   respected   ADJ Degree=Pos  7   amod    _   _
7   cleric  cleric  NOUN    Number=Sing 3   nmod    _   _
8   will    will    AUX VerbForm=Fin    10  aux _   _
9   be  be  AUX VerbForm=Inf    10  aux _   _
10  causing cause   VERB    VerbForm=Ger    0   root    _   _
11  us  we  PRON    Case=Acc|Number=Plur|Person=1|PronType=Prs  10  iobj    _   _
12  trouble trouble NOUN    Number=Sing 10  dobj    _   _
13  for for ADP _   14  case    _   _
14  years   year    NOUN    Number=Plur 10  nmod    _   _
15  to  to  PART    _   16  mark    _   _
16  come    come    VERB    VerbForm=Inf    14  acl _   _
17  .   .   PUNCT   _   10  punct   _   _
18  ]   ]   PUNCT   _   10  punct   _   _

1   DPA DPA PROPN   Number=Sing 0   root    _   _
2   :   :   PUNCT   _   1   punct   _   _
3   Iraqi   iraqi   ADJ Degree=Pos  4   amod    _   _
4   authorities authority   NOUN    Number=Plur 5   nsubj   _   _
5   announced   announce    VERB    Mood=Ind|Tense=Past|VerbForm=Fin    1   parataxis   _   _
6   that    that    SCONJ   _   9   mark    _   _
7   they    they    PRON    Case=Nom|Number=Plur|Person=3|PronType=Prs  9   nsubj   _   _
8   had have    AUX Mood=Ind|Tense=Past|VerbForm=Fin    9   aux _   _
9   busted  bust    VERB    Tense=Past|VerbForm=Part    5   ccomp   _   _
10  up  up  ADP _   9   compound:prt    _   _
11  3   3   NUM NumType=Card    13  nummod  _   _
12  terrorist   terrorist   ADJ Degree=Pos  13  amod    _   _
13  cells   cell    NOUN    Number=Plur 9   dobj    _   _
14  operating   operate VERB    VerbForm=Ger    13  acl _   _
15  in  in  ADP _   16  case    _   _
16  Baghdad Baghdad PROPN   Number=Sing 14  nmod    _   _
17  .   .   PUNCT   _   1   punct   _   _

What's wrong with my colums? Thanks in advance.

**Comment by onedash** [comment]
Did you change a train **confinguration file** (-c option), can you provide it?

**Comment by MinionAttack** [comment]
I'm using the configuration files from here [https://github.com/emorynlp/nlp4j/tree/master/src/main/resources/edu/emory/mathcs/nlp/configuration](url)

I'm ussing **config-train-dep.xml** or I should use other? I don't know if I have to use that or **config-train-sample.xml** or **config-train-sample-optimized.xml** :/

**Comment by MinionAttack** [comment]
Please, someone can help me?

**Comment by MinionAttack** [comment]
I found the error, when I downloaded the config files maybe get corrupted. I downloaded again and now seems to be correct.

**Comment by jdchoi77** [comment]
Sorry; I didn't get to check this issue until now.  When you have more issues, could you please post it to our discussion group: https://groups.google.com/forum/#!forum/emorynlp.  Thank you!
